[SYCL][Graph] Make internal constructor private
reble/llvm pull request #219
Opened 2023-06-09 17:58 UTC by reble

Addresses: https://github.com/intel/llvm/pull/9728/files/5ae93e351d53647bbac3a30cad84e50ddfc16a58#r1220852359

2023-06-12 08:57 UTC, EwanC requested changes
I see a build error with this change.
```
/home/ewan/Development/dpcpp/sycl/source/detail/graph_impl.cpp:327:74: error: ‘sycl::_V1::ext::oneapi::experimental::command_graph<sycl::_V1::ext::oneapi::experimental::graph_state::executable>::command_graph(const std::shared_ptr<sycl::_V1::ext::oneapi::experimental::detail::graph_impl>&, const sycl::_V1::context&)’ is private within this context
  327 |                                                 this->impl->get_context()};
      |                                                                          ^
```

I'm wondering if we can remove the `command_graph(const std::shared_ptr<detail::graph_impl> &Impl) : impl(Impl)` constructor mentioned in the comment instead actually.

2023-06-13 04:25 UTC, reble commented
> I see a build error with this change.
> 
> ```
> /home/ewan/Development/dpcpp/sycl/source/detail/graph_impl.cpp:327:74: error: ‘sycl::_V1::ext::oneapi::experimental::command_graph<sycl::_V1::ext::oneapi::experimental::graph_state::executable>::command_graph(const std::shared_ptr<sycl::_V1::ext::oneapi::experimental::detail::graph_impl>&, const sycl::_V1::context&)’ is private within this context
>   327 |                                                 this->impl->get_context()};
>       |                                                                          ^
> ```
> 
> I'm wondering if we can remove the `command_graph(const std::shared_ptr<detail::graph_impl> &Impl) : impl(Impl)` constructor mentioned in the comment instead actually, as it's unused in this branch. I'd guess the reason it's private though, is that it would be used by the `friend` interface for `friend T sycl::detail::createSyclObjFromImpl(decltype(T::impl) ImplObj);`

Not sure how easy that is, and it wouldn't really fix the issue. Just push it out for later. How about declaring the `command_graph<modifiable>` as a friend?

2023-06-13 13:25 UTC, Bensuo commented
> Not sure how easy that is, and it wouldn't really fix the issue. Just push it out for later. How about declaring the `command_graph<modifiable>` as a friend?

I think adding it as a friend is fine, and is pretty common practice for this kind of case, if it fixes the compilation issues and works correctly.

However, probably the better way to do this would be to just use `detail::createSyclObjFromImpl()` when we create the executable graph rather than call the constructor ourselves. Then we could remove the constructor taking a context and just keep the single private one. We should probably also move the tag into the impl if we did that, although I think it's currently unused.

2023-06-14 16:11 UTC, EwanC approved these changes

2023-06-14 17:39 UTC, Bensuo approved these changes

2023-06-14 21:27 UTC, merged